name: iml_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - lightgbm
  - plotly
  - pip
  - ipykernel
  - plotly
  - pip:
    - optuna
    - optunahub
    - pytorch-tabnet